### ISSUE TITLE
Is there a limit on users visible in the UI?

### ISSUE THREAD

**Issue by MonsterBA** [ForceDotComLabs/QuotaEdit#38]
In my current org, I seem to be limited to 999 users that would be visible in our Edit Quota object.  Is this by design?  can I expand the number in the UI?  We do have more than 1000 users set as Forecast enabled, and it would be helpful to see all users in the UI.  Thanks.

**Comment by alonkama** [comment]
There is a Salesforce limit on the number of records returned by the query.
One day I will try adding a pagination, so I'll keep your suggestion as a
feature request.

For now, the best practice is to define quota managers further down the
hierarchy and let them enter quotas only for their role and subroles.

On Mar 2, 2016, at 12:24 PM, MonsterBA <notifications@github.com> wrote:

In my current org, I seem to be limited to 999 users that would be visible
in our Edit Quota object. Is this by design? can I expand the number in the
UI? We do have more than 1000 users set as Forecast enabled, and it would
be helpful to see all users in the UI. Thanks.

—
Reply to this email directly or view it on GitHub
<https://github.com/ForceDotComLabs/QuotaEdit/issues/38>.

**Comment by MonsterBA** [comment]
Thank you for the quick reply.  Do you happen to know if the SF limit is in fact 999?

**Comment by alonkama** [comment]
Yes, the limit is 999.

**Comment by alonkama** [comment]
In version 2.1 (updated today), you can get around this limit. The user can now choose a specific role from the Forecast Hierarchy, and the app will allow setting the quota for just the users in that role or below it. Give it a try and please reopen if there is still an issue.
