### ISSUE TITLE
Can i have two line items for a salespersons quota

### ISSUE THREAD

**Issue by agunnink** [ForceDotComLabs/QuotaEdit#45]
I want to split my reps quotas. Existing Business and New Business can I do that with your tool??

Please let me know. abbe.gunnink@foxt.com

**Comment by alonkama** [comment]
It's not a capability of the tool because the underlying Collaborative Forecasts doesn't support multiple quotas per period for the same Forecasting Type. 

You can look into achieving this with different Product Families, or with forecasting on a custom currency field. And then this tool will support adding quotas for any of those Forecasting Types. For more information, check out Salesforce's Forecasting Implementation Guide: http://resources.docs.salesforce.com/200/20/en-us/sfdc/pdf/forecasts.pdf
