### ISSUE TITLE
Quotas not changing previously uploaded values

### ISSUE THREAD

**Issue by shippconsulting** [ForceDotComLabs/QuotaEdit#55]
I used the API to upload the quotas and now want to use Edit Quotas for future changes.  I typed in the quota for January 2017, since Edit Quotas did not bring over the current values.  I then changed one of the values to make sure that I was actually updating the quotas, and the quota did not change.  How do you get Edit Quotas to overwrite what was uploaded via the API?

I can be reached at teri@shippconsulting.com or 508-259-9997.

Thanks,
Teri Shipp

**Comment by alonkama** [comment]
Teri, is it possible for you to upload screenshots of the Edit Quotas screen and the Forecasting tab? If you can't because it's exposing your personal data, then we'll try a different way.

The quota via Edit Quotas is exactly the same object as via API. If you're not seeing the same value, then please double-check:
1. The period (are you sure you're entering for **2017**?)
2. The forecasting type, if you have more than one beyond Opportunity Revenue.

**Comment by shippconsulting** [comment]
I had not even noticed that is was 2016. Thank you, it looks great now!

**Comment by alonkama** [comment]
I'm glad it worked out.
